controller_list:
  - name: r2/l_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - r2/left_arm/joint0
      - r2/left_arm/joint1
      - r2/left_arm/joint2
      - r2/left_arm/joint3
      - r2/left_arm/joint4
      - r2/left_arm/wrist/pitch
      - r2/left_arm/wrist/yaw
  - name: r2/r_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - r2/right_arm/joint0
      - r2/right_arm/joint1
      - r2/right_arm/joint2
      - r2/right_arm/joint3
      - r2/right_arm/joint4
      - r2/right_arm/wrist/pitch
      - r2/right_arm/wrist/yaw
  - name: r2/l_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - r2/left_arm/hand/index/yaw
      - r2/left_arm/hand/index/proximal
      - r2/left_arm/hand/index/medial
      - r2/left_arm/hand/index/distal
      - r2/left_arm/hand/middle/yaw
      - r2/left_arm/hand/middle/proximal
      - r2/left_arm/hand/middle/medial
      - r2/left_arm/hand/middle/distal
      - r2/left_arm/hand/little/proximal
      - r2/left_arm/hand/little/medial
      - r2/left_arm/hand/little/distal
      - r2/left_arm/hand/ring/proximal
      - r2/left_arm/hand/ring/medial
      - r2/left_arm/hand/ring/distal
      - r2/left_arm/hand/thumb/roll
      - r2/left_arm/hand/thumb/proximal
      - r2/left_arm/hand/thumb/medial
      - r2/left_arm/hand/thumb/distal
  - name: r2/r_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - r2/right_arm/hand/index/yaw
      - r2/right_arm/hand/index/proximal
      - r2/right_arm/hand/index/medial
      - r2/right_arm/hand/index/distal
      - r2/right_arm/hand/middle/yaw
      - r2/right_arm/hand/middle/proximal
      - r2/right_arm/hand/middle/medial
      - r2/right_arm/hand/middle/distal
      - r2/right_arm/hand/little/proximal
      - r2/right_arm/hand/little/medial
      - r2/right_arm/hand/little/distal
      - r2/right_arm/hand/ring/proximal
      - r2/right_arm/hand/ring/medial
      - r2/right_arm/hand/ring/distal
      - r2/right_arm/hand/thumb/roll
      - r2/right_arm/hand/thumb/proximal
      - r2/right_arm/hand/thumb/medial
      - r2/right_arm/hand/thumb/distal
  - name: r2/neck_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - r2/neck/joint0
      - r2/neck/joint1
      - r2/neck/joint2
  - name: r2/waist_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - r2/waist/joint0
  - name: r2/l_leg_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - r2/left_leg/joint0
      - r2/left_leg/joint1
      - r2/left_leg/joint2
      - r2/left_leg/joint3
      - r2/left_leg/joint4
      - r2/left_leg/joint5
      - r2/left_leg/joint6
  - name: r2/r_leg_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - r2/right_leg/joint0
      - r2/right_leg/joint1
      - r2/right_leg/joint2
      - r2/right_leg/joint3
      - r2/right_leg/joint4
      - r2/right_leg/joint5
      - r2/right_leg/joint6
  - name: r2/l_foot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - r2/left_leg/gripper/joint0
      - r2/left_leg/gripper/jawLeft
      - r2/left_leg/gripper/jawRight
  - name: r2/r_foot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - r2/right_leg/gripper/joint0
      - r2/right_leg/gripper/jawLeft
      - r2/right_leg/gripper/jawRight
