controller_list:
  - name: fake_left_arm_controller
    joints:
      - r2/left_arm/joint0
      - r2/left_arm/joint1
      - r2/left_arm/joint2
      - r2/left_arm/joint3
      - r2/left_arm/joint4
      - r2/left_arm/wrist/pitch
      - r2/left_arm/wrist/yaw
  - name: fake_right_arm_controller
    joints:
      - r2/right_arm/joint0
      - r2/right_arm/joint1
      - r2/right_arm/joint2
      - r2/right_arm/joint3
      - r2/right_arm/joint4
      - r2/right_arm/wrist/pitch
      - r2/right_arm/wrist/yaw
  - name: fake_left_hand_controller
    joints:
      - r2/left_arm/hand/index/yaw
      - r2/left_arm/hand/index/proximal
      - r2/left_arm/hand/index/medial
      - r2/left_arm/hand/index/distal
      - r2/left_arm/hand/middle/yaw
      - r2/left_arm/hand/middle/proximal
      - r2/left_arm/hand/middle/medial
      - r2/left_arm/hand/middle/distal
      - r2/left_arm/hand/little/proximal
      - r2/left_arm/hand/little/medial
      - r2/left_arm/hand/little/distal
      - r2/left_arm/hand/ring/proximal
      - r2/left_arm/hand/ring/medial
      - r2/left_arm/hand/ring/distal
      - r2/left_arm/hand/thumb/roll
      - r2/left_arm/hand/thumb/proximal
      - r2/left_arm/hand/thumb/medial
      - r2/left_arm/hand/thumb/distal
  - name: fake_right_hand_controller
    joints:
      - r2/right_arm/hand/index/yaw
      - r2/right_arm/hand/index/proximal
      - r2/right_arm/hand/index/medial
      - r2/right_arm/hand/index/distal
      - r2/right_arm/hand/middle/yaw
      - r2/right_arm/hand/middle/proximal
      - r2/right_arm/hand/middle/medial
      - r2/right_arm/hand/middle/distal
      - r2/right_arm/hand/little/proximal
      - r2/right_arm/hand/little/medial
      - r2/right_arm/hand/little/distal
      - r2/right_arm/hand/ring/proximal
      - r2/right_arm/hand/ring/medial
      - r2/right_arm/hand/ring/distal
      - r2/right_arm/hand/thumb/roll
      - r2/right_arm/hand/thumb/proximal
      - r2/right_arm/hand/thumb/medial
      - r2/right_arm/hand/thumb/distal
  - name: fake_head_controller
    joints:
      - r2/neck/joint0
      - r2/neck/joint1
      - r2/neck/joint2
  - name: fake_waist_controller
    joints:
      - r2/waist/joint0
  - name: fake_both_arms_controller
    joints:
      - r2/left_arm/joint0
      - r2/left_arm/joint1
      - r2/left_arm/joint2
      - r2/left_arm/joint3
      - r2/left_arm/joint4
      - r2/left_arm/wrist/pitch
      - r2/left_arm/wrist/yaw
      - r2/right_arm/joint0
      - r2/right_arm/joint1
      - r2/right_arm/joint2
      - r2/right_arm/joint3
      - r2/right_arm/joint4
      - r2/right_arm/wrist/pitch
      - r2/right_arm/wrist/yaw
