left_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
right_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
head:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
