left_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
right_arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
#  solve_type: Distance
head:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
