left_arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
right_arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
head:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
